//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


//aww yeaaaa
function addFibEvens () {
	function fibBuilder (){
		var fibs = [1,2];
		
		while((fibs[fibs.length - 1] + fibs[fibs.length - 2]) < 4000000){
			fibs[fibs.length] = fibs[fibs.length - 1] + fibs[fibs.length - 2]
		}
		return fibs;
	}
	
	var fibs = fibBuilder();

	return fibs.filter(num => num % 2 === 0).reduce((prev, curr) => prev + curr);
}

//4613732